### PR TITLE
Bump to 2.0.0

### LINKED ISSUE #114: Publish null safe stable version

### PR DESCRIPTION
**Pull request by guidezpl**
Fixes #114

### CODE REVIEW

**Comment by guidezpl** [comment]
@brianegan Could you take a look? Thanks!

**Comment by brianegan** [comment]
LGTM! Thanks for the PR.

**Comment by guidezpl** [comment]
Np, do you have access to publish because I don't

**Comment by brianegan** [comment]
Yes, but i found one more thing that needs to be adjusted. Apologies, life is very busy for me atm. I'll hopefully publish today

**Comment by brianegan** [comment]
2.0.0 is now published.

I was getting a warning about 2.0.0 supporting a pre-release of flutter / dart. I decided to ignore that warning for now, since there shouldn't be any harm in supporting those versions (which worked with the pre-release).

**Pull request merged**
